### ISSUE TITLE
Implement data-plane functionality on FRR

### ISSUE THREAD

**Issue by josecastillolema** [redhat-performance/web-burner#39]
Today FRR only handles control plane BFD connections. It would be interesting to extend it to support OVN Kubernetes Multiple External Gateway capability data plane.

Today, the tester workflows consists on:
- Run the tests
- After the test is run (and the test resources have to be kept for this reason) check OVN constructs (lr-routes, lr-policies, bfd sessions, etc.)
- Delete the resources of the test

If the data plane were properly established, the OVN checking could be transformed into pod readiness policies (i.e.: ping external IP, etc.) that would deliver PASS/FAIL conditions without the need of manually checking OVN constructs and easing the integration into CI pipelines.

We can take a look at @williamcaban [FRRouting Based OCP Multiple External Gateway](https://github.com/williamcaban/frr-gw/) effort as a starting point.

**Comment by josecastillolema** [comment]
It would also be an opportunity to update the FRR image we are using `quay.io/fpaoline/ovnkbfdtest:0.2`.
There are newer and officially supported images.

**Comment by josecastillolema** [comment]
Was able to establishing pod readiness checks based on validating they can reach a network running in a container's looback address via an external gateway. Process documented [here](https://josecastillolema.github.io/icni2/).
Next steps:
 - validate the procedure in the lab
 - make the corresponding adjustments to web-burner templates

**Comment by josecastillolema** [comment]
Included pod readiness checks for the BFD sessions as well and updated the doc ^:
```
    readinessProbe:
      exec:
        command:
          - sh
          - -c
          - >-
             vtysh -c 'show bfd peers brief' |
             grep up
      initialDelaySeconds: 5
      periodSeconds: 5  
```
